### ISSUE TITLE
API docs link from README results in 404

### ISSUE THREAD

**Issue by sjamaan** [taoensso/timbre#377]
The API docs are not available anymore, or at least not under the URL in the link from the `README`. If I click the link, it just says `404 not found`. [Site not found](http://ptaoussanis.github.io/timbre/)

**Comment by ptaoussanis** [comment]
@sjamaan Hi Peter, thanks for pinging about this! Apologies for the trouble, will get the links fixed in the next few hours.

Details: I've been re-organizing all my libraries lately, and updating documentation. Still need to update everything for Timbre, and hadn't realised that I'd broken something in the meantime with a change in one of the domains.

**Comment by ptaoussanis** [comment]
This should now be fixed 👍 Again, sorry for the trouble.

Relatedly, aiming to get the Timbre docs properly updated within the next 2 weeks or so.

**Comment by sjamaan** [comment]
Many thanks :pray:
